name: Issue Triage

on:
  issues:
    types: [labeled]

jobs:
  issue-creation:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        tag-mappings: [{
          bug: issue-transfer,
          trill: tronic
        }]
    steps:
      - name: Verify Tag
        id: verify-tag
        uses: actions/github-script@v5
        with:
          script: |
            const label = context.payload.label.name;
            const mappings = ${{ toJson(matrix.tag-mappings) }};
            for (const [key, value] of Object.entries(mappings)) {
              if (label == key) {
                return value;
              }
            }
            return '';
          result-encoding: string
      - name: Check if Triage Label Needs to be Created
        uses: actions/github-script@v5
        if: steps.verify-tag.outputs.result != '' && github.event.issue.state == 'open'
        with:
          github-token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          script: |
            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: `${{ steps.verify-tag.outputs.result }}`,
            });
            if (labels.data.filter(e => e.name === 'Needs Triage').length <= 0) {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: `${{ steps.verify-tag.outputs.result }}`,
                name: 'Needs Triage',
                color: 'FF0000',
              });
            }
      - name: Transfer issue
        run: hub issue transfer 12 thinktandem/issue-transfer
        env:
          GITHUB_TOKEN: ${{ secrets.TRANSFER_ISSUE_TOKEN }}