name: Issue Triage

on:
  issues:
    types: [labeled]

jobs:
  issue-creation:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        tag-mappings: [{
          bug: issue-transfer,
          trill: tronic
        }]
    steps:
      - uses: actions/checkout@v2
      - name: Verify Tag
        id: verify-tag
        uses: actions/github-script@v5
        with:
          script: |
            const label = context.payload.label.name;
            const mappings = ${{ toJson(matrix.tag-mappings) }};
            for (const [key, value] of Object.entries(mappings)) {
              if (label == key) {
                return value;
              }
            }
            return '';
          result-encoding: string
      - name: Check if Triage Label Needs to be Created
        uses: actions/github-script@v5
        if: steps.verify-tag.outputs.result != '' && github.event.issue.state == 'open'
        with:
          github-token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          script: |
            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: `${{ steps.verify-tag.outputs.result }}`,
            });
            if (labels.data.filter(e => e.name === 'Needs Triage').length <= 0) {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: `${{ steps.verify-tag.outputs.result }}`,
                name: 'Needs Triage',
                color: 'FF0000',
              });
            }
      - name: Transfer Issue & Create Stub
        id: transfer-issue
        uses: lando/transfer-issue-action@1.0.0
        if: steps.verify-tag.outputs.result != ''
        with:
          github_token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          destination_repo: ${{ steps.verify-tag.outputs.result }}
      - name: Finalize Issue Tags
        uses: actions/github-script@v5
        if: steps.transfer-issue.outputs.transferred_issue_number != ''
        with:
          github-token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          script: |
            const transferredIssueNumber = ${{ steps.transfer-issue.outputs.transferred_issue_number }};

            let transferredIssue = await github.rest.issues.update({
              issue_number: transferredIssueNumber,
              owner: context.repo.owner,
              repo: `${{ steps.verify-tag.outputs.result }}`,
              labels: ['Needs Triage']
            });