name: Issue Triage

on:
  issues:
    types: [labeled]

jobs:
  issue-creation:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        tag-mappings: [{
          bug: issue-transfer,
          trill: tronic
        }]
    steps:
      - uses: actions/checkout@v2
      - name: Verify Tag
        id: verify-tag
        uses: actions/github-script@v5
        with:
          script: |
            const label = context.payload.label.name;
            const mappings = ${{ toJson(matrix.tag-mappings) }};
            for (const [key, value] of Object.entries(mappings)) {
              if (label == key) {
                return value;
              }
            }
            return '';
          result-encoding: string
      - name: Check if Triage Label Needs to be Created
        uses: actions/github-script@v5
        if: steps.verify-tag.outputs.result != '' && github.event.issue.state == 'open'
        with:
          github-token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          script: |
            hub issue transfer 10 thinktandem/issue-transfer