name: Issue Triage

on:
  issues:
    types: [opened]

jobs:
  issue-creation:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - name: Echo
        uses: echo ${{ github.event.issue }}

