name: Issue Triage

on:
  issues:
    types: [labeled]

jobs:
  issue-creation:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Parse Mappings
        id: parse
        uses: KJ002/read-yaml@1.5
        with:
          file: 'files/tag-mapping.yml'
          key-path: '["mappings"]'
      - name: Verify output
        run: |
          echo "${{ steps.parse.data }}"
      - name: Transfer Issue
        uses: actions/github-script@v5
        if: ${{ github.event.issue.state == 'open' }}
        with:
          github-token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: 'thinktandem',
              repo: 'issue-transfer',
              title: `${{ github.event.issue.title }}`,
              body: `${{ github.event.issue.body }}`,
              assignees: [
                `${{ github.event.issue.user.login }}`
              ]
            })
      - name: Close Current Issue
        uses: actions/github-script@v5
        if: ${{ github.event.issue.state == 'open' }}
        with:
          github-token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          script: |
            github.rest.issues.update({
              issue_number: `${{ github.event.issue.number }}`,
              owner: `${{ github.event.organization.login }}`,
              repo: `${{ github.event.repository.name }}`,
              state: 'closed'
            })