name: Issue Triage

on:
  issues:
    types: [labeled]

jobs:
  issue-creation:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Transfer Issue
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.create({
              owner: thinktandem,
              repo: issue-transfer,
              title: ${{ github.event.issue.title }},
              body: ${{ github.event.issue.title }},
              assignees: [
                ${{ github.event.issue.user.login }}
              ]
            })